### ISSUE TITLE
code for assetatm not available

### ISSUE THREAD

**Issue by InfiniticGit** [ATM-Consulting/dolibarr_package_asset#1]
Hello, 
I try to reach the public repository "assetatm @ 4c172b8" but it is not available...404 error

Is it possible to access to the code of this module ?

Thanks in advance
Infinitic

**Comment by Projets-ACTI** [comment]
up

**Comment by atm-john** [comment]
Hi,

Repository is private.
Code is available here : https://www.dolistore.com/en/modules/624-Asset-and-Dispatch.html

Have a nice day
